In [2]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np


# create a 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
1
(5,)


In [ ]:
# reshape into 2d
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5)               # 1 row 5 columns
print(arr2)
print(arr2.ndim)
print(arr2.shape)   

[[1 2 3 4 5]]
2
(1, 5)


In [10]:
# 
arr2 = np.array([[1,2,3,4,5]])
print(arr2)

[[1 2 3 4 5]]


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
# print(arr2.ndim)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
